#!/usr/bin/env bash
# get info about subdomains

dig_record () {
    res=$(dig $1 | grep -A1 ";; ANSWER SECTION:" | grep -i "$1" | awk '{print $4}')
    echo $res
}

dig_ip () {
    res=$(dig $1 | grep -A1 ";; ANSWER SECTION:" | grep -i "$1" | awk '{print $5}')
    echo $res
}

# The subdomain [SUB_DOMAIN] is a [RECORD_TYPE] record and points to [DESTINATION]
dig_subdomains () {
    # no_dots=$(echo "$1" | tr -cd "." | wc -c)
    if [[ $# -lt 2 ]]; then
    echo The subdomain www is a $(dig_record www."$1") record and points to $(dig_ip www."$1")
    echo The subdomain lb-01 is a $(dig_record lb-01."$1") record and points to $(dig_ip lb-01."$1")
    echo The subdomain web-01 is a $(dig_record web-01."$1") record and points to $(dig_ip web-01."$1")
    echo The subdomain web-02 is a $(dig_record web-02."$1") record and points to $(dig_ip web-02."$1")
    else
    # subdomain=$(awk -F. '{print $1}')
    echo The subdomain "$2" is a $(dig_record "$2"."$1") record and points to $(dig_ip "$2"."$1")
    fi
}

dig_subdomains $1 $2