#!/usr/bin/env bash
# configure an Nginx server to redirect

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo ufw allow 'Nginx HTTP'
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=mHVABLIbsc8 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
