#!/usr/bin/env bash
# configure the load balancer

sudo apt-get -y update

sudo apt-get -y install haproxy
sudo chmod 766 /etc/default/haproxy
sudo chmod 766 /etc/haproxy/haproxy.cfg
echo -e "\nfrontend http_front\n\tbind *:80\n\tmode http\n\tdefault_backend http_back\n\n backend http_back\n\tbalance roundrobin\n\tserver 433823-web-01 100.25.144.102:80 check\n\tserver 433823-web-02 34.207.58.33:80 check\n" >> /etc/haproxy/haproxy.cfg 
sudo service haproxy restart
