#!/usr/bin/env bash
# Install your load balancer
sudo apt-get -y update

sudo apt-get -y install haproxy

sudo chown  $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend front
    bind *:80
    mode http
    default_backend back
backend back
    balance roundrobin
    server 433823-web-01 52.23.179.58:80 check
    server 433823-web-02 54.90.36.155:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
