#!/usr/bin/env bash
# handle signals


trap "echo 'Y U no love me?!'" SIGINT
trap "rm -r '/var/run/myscript.pid'; break"  SIGQUIT
trap "echo 'I hate the kill command'; rm -r '/var/run/myscript.pid'; break" SIGTERM

touch "/var/run/myscript.pid"
while true
do
echo "To infinity and beyond"
sleep 2
done