#!/usr/bin/env bash
# check files

if [[ -e "school" ]]
then
echo "school file exists"
else
echo "school file does not exist"
fi
if [[ ! -s "school" && -e "school" ]]
then
echo "school file is empty"
elif [[ -s "school" && -e "school" ]]
then
echo "school file is not empty"
fi
# if [[ -f "school" && -e "school" ]]
# echo "school is a regular file"
# fi