#!/usr/bin/env bash
# debugging a web stack

sudo get-apt -y update
sudo get-apt install -y apache2
sudo service apache2 start
echo "Hello Holberton" | sudo tee /var/www/html/index.html
sudo systemctl restart apache2
